### ISSUE TITLE
Enregistrement d'un nouveau vendeur

### ISSUE THREAD

**Issue by ThomasEscorne** [Jaoued-mtd/easy_front#1]
Je n'arrive pas a ajouter un nouveau vendeur via le form => https://github.com/Jaoued-mtd/easy_front

**Comment by Jaoued-mtd** [comment]
Bonjour Thomas, 

Merci pour ton retour, en effet je viens d'ajouter la gestion d'erreur afin d'améliorer l'expérience des utilisateurs sur l'appli Easyimo. Voici quelques exemples de message pour la création, suppression ou modification d'un vendeur :

![erreur](https://user-images.githubusercontent.com/68811444/90539637-608ae400-e180-11ea-9781-4acb776dce8f.png)
![vendeur](https://user-images.githubusercontent.com/68811444/90539667-6b457900-e180-11ea-926e-d58ffdd34e39.png)
![modif](https://user-images.githubusercontent.com/68811444/90539693-76000e00-e180-11ea-8ccb-39ab1476dd06.png)

Je reste disponible pour toute information complémentaire.
Jaoued.
