### ISSUE TITLE
Photo de profil

### ISSUE THREAD

**Issue by ThomasEscorne** [Jaoued-mtd/easy_front#2]
Ma photo de profil ne se met pas à jour quand j'essaie de l'uploader dans l'interface de mon profil => https://gifted-lewin-0b6ac1.netlify.app/profil#

**Comment by Jaoued-mtd** [comment]
Bonjour Thomas, 
Il est de nouveau possible de modifier ton image de profil à la création d'un compte il y a une image par défaut : 
![Henri1](https://user-images.githubusercontent.com/68811444/90666345-8631ef00-e24d-11ea-9e1b-03c7af7cee53.png)

Il est possible de changer ton image de profil grace à l'espace dans la page profil : 
![image modif](https://user-images.githubusercontent.com/68811444/90666383-94800b00-e24d-11ea-8b99-636b01c4e75d.png)

Merci ! 

Je reste disponible pour toute information complémentaire.
Jaoued
